### PR TITLE
Improve layout on varied screen sizes

### PR DESCRIPTION
**Pull request by cbaines**
These css changes help prevent elements from overlapping, and make the pages display larger on mobile devices.

I have tried to maintain the current layout, the only change I intended to make is to move the date which the data was updated to the footer (and I don't mind reverting this).

I have also made some changes to the JavaScript, a few small bug fixes, and a minimum height for the box to make it usable regardless of the screen size.

### CODE REVIEW

**Comment by joto** [comment]
Quite a few improvements! Thank you!

I played around with it a bit, and I think the move of the date to the bottom is a problem: First it leads to every page being a tiny bit too tall which will give it a scroll bar. We could fix this, but it would still take up space making the content area smaller. At the top this didn't really matter, because we had the space anyway, because of the logo. I think we should move the date back up top and just not show it when the window gets too small. The information is available behind the "source" link, that's good enough for small screens.

Not sure about the footer yet, it is an improvement that the left and right part don't move on top of each other any more. But it could also lead to the page being the wrong height. We can see this once the date isn't at the bottom any more. And the height of the flexigrid tables is now smaller leaving some space empty below them.

As far as I can see these are the only change that also affects the display on large screens. Everything else, while not being perfect, at least makes things better for small screens while leaving the experience on the large screen the same.

**Comment by cbaines** [comment]
I have put the date back at the top, and have made some alterations that should help it match the current layout.

As for the footer, as I have added the ui-helper-clearfix class, the size of the element should properly represent the content when it overlaps. I still can't quite get the footer to line up as before, but I have got the scroll bar to disappear.

**Comment by joto** [comment]
I still get the scroll bar and there is still too much space at the bottom of the page and a the bottom of the grey box. The height calculations are all rather sensitive, because there are slightly different layouts on different pages, some with tabs, some without etc.

I have now cherry-picked some of your commits and added some of my own. The date is gone on smaller displays. I used your pre-text changes and put them on all pages, so the header and intro texts and tools now warp nicely. I left the language choice and search alone for the moment, I think they should be moved into a menu anyway. And the footer is still overlapping. But this way I got no scroll bars and all the pages look still the same on large screens while being an improvement for small ones. I have rolled this out already. Lets use this as a base for further improvements.

**Comment by cbaines** [comment]
Great, I'll close this pull request then.

**Pull request closed without merging**
